[versions]
loom = "1.14-SNAPSHOT"
kotlin = "2.3.0"
spotless = "8.1.0"

minecraft = "1.18.2"
fabric-loader = "0.18.1"
fabric-api = "0.77.0+1.18.2"
fabric-kotlin = "1.13.8+kotlin.2.3.0"

modmenu = "3.2.5"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
fabric-junit = { module = "net.fabricmc:fabric-loader-junit", version.ref = "fabric-loader" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]
loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "loom" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
